name: 改善・リファクタ
description: 改善・リファクタはこちら
body:
  - type: textarea
    id: background
    attributes:
      label: 背景
      description: どのような課題を抱えてissueを立てたのか、経緯や前提を記載してください。
    validations:
      required: true
  - type: textarea
    id: merit
    attributes:
      label: メリット
      description: 改善することでどのようなメリットがあるのかを記載してください。
  - type: textarea
    id: do
    attributes:
      label: やること
      description: このissueで取り組むことを記載してください。
  - type: textarea
    id: supplement
    attributes:
      label: 補足/キャプチャ
  - type: dropdown
    id: importance
    attributes:
      label: 重要度
      description: このissueの重要度を選択したください。（主観でOK）
      options:
        - 高
        - 中
        - 低
  - type: dropdown
    id: urgency
    attributes:
      label: 緊急度
      description: このissueの緊急度を選択したください。（主観でOK）
      options:
        - 高
        - 中
        - 低
